import { NextResponse } from 'next/server';
import * as XLSX from 'xlsx';
import { adminClient, publicClient } from '../../../../lib/supabase-server';

export const runtime='nodejs';
const clean=v=>v==null?'':String(v).replace(/\u00A0/g,' ').replace(/\s+/g,' ').trim();
function toNumber(v){if(typeof v==='number'&&Number.isFinite(v))return v;if(v==null||v==='')return 0;let s=String(v).trim().replace(/\s/g,'').replace(/Rp/gi,'');if(!s)return 0;const neg=/^\(.*\)$/.test(s);s=s.replace(/[()]/g,'');if(s.includes('.')&&s.includes(',')){if(s.lastIndexOf(',')>s.lastIndexOf('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'');}else if((s.match(/\./g)||[]).length>1)s=s.replace(/\./g,'');else if((s.match(/,/g)||[]).length>1)s=s.replace(/,/g,'');else if(s.includes(',')&&!s.includes('.')){const parts=s.split(',');s=parts[1]?.length===3?parts.join(''):s.replace(',','.')}const n=Number(s);return Number.isFinite(n)?(neg?-Math.abs(n):n):0;}
function field(r,names){const wanted=names.map(x=>x.toLowerCase());const k=Object.keys(r).find(x=>wanted.includes(String(x).trim().toLowerCase()));return k===undefined?'':r[k];}
function row(r,period){return {period,company_code:clean(field(r,['Company Code'])),account:clean(field(r,['Account'])),document_number:clean(field(r,['Document Number'])),document_type:clean(field(r,['Document Type'])),reference:clean(field(r,['Reference'])),invoice_reference:clean(field(r,['Invoice reference'])),document_date:clean(field(r,['Document Date']))||null,posting_date:clean(field(r,['Posting Date']))||null,due_date:clean(field(r,['Due Date']))||null,quantity:toNumber(field(r,['Quantity'])),amount:toNumber(field(r,['Amount in local currency'])),local_currency:clean(field(r,['Local Currency'])),amount_document_currency:toNumber(field(r,['Amount in doc. curr.'])),document_currency:clean(field(r,['Document currency'])),document_header_text:clean(field(r,['Document Header Text'])),text:clean(field(r,['Text'])),purchasing_document:clean(field(r,['Purchasing Document'])),status:clean(field(r,['Status'])),status_grouping:clean(field(r,['Status Grouping'])),vendor_code:clean(field(r,['Kode Vendor'])),vendor_name:clean(field(r,['Nama Vendor'])),plant:clean(field(r,['Plant'])),user_name:clean(field(r,['User Name'])),category:clean(field(r,['Kategori'])),due_status:clean(field(r,['Jatuh Tempo'])),age:toNumber(field(r,['Umur'])),age_group:clean(field(r,['Umur Hutang'])),remark:clean(field(r,['Remark'])),action:clean(field(r,['Action'])),remark_po:clean(field(r,['Remark PO'])),remark_rekon:clean(field(r,['Remark Tim Rekon'])),confirmation:clean(field(r,['Konfirmasi'])),concenate:clean(field(r,['Concenate'])),snapshot_date:period};}
function inferPeriod(name){const m=String(name).match(/(\d{2})[._-]?(\d{2,4})/);if(!m)return '';const year=m[2].length===2?`20${m[2]}`:m[2];return `${year}-${m[1]}-01`;}
export async function POST(req){try{const auth=req.headers.get('authorization')||'';const token=auth.replace(/^Bearer\s+/i,'');if(!token)return NextResponse.json({error:'Login admin diperlukan.'},{status:401});const pub=publicClient();const {data:{user},error:userErr}=await pub.auth.getUser(token);if(userErr||!user)return NextResponse.json({error:'Sesi admin tidak valid.'},{status:401});if(process.env.ADMIN_EMAIL&&user.email?.toLowerCase()!==process.env.ADMIN_EMAIL.toLowerCase())return NextResponse.json({error:'Akun bukan admin.'},{status:403});const form=await req.formData();const file=form.get('file');if(!file)return NextResponse.json({error:'File Excel tidak ditemukan.'},{status:400});const buf=Buffer.from(await file.arrayBuffer());const wb=XLSX.read(buf,{type:'buffer',cellDates:true});const ws=wb.Sheets['Data Source'];if(!ws)return NextResponse.json({error:'Sheet Data Source tidak ditemukan.'},{status:400});const raw=XLSX.utils.sheet_to_json(ws,{defval:'',raw:true});if(!raw.length)return NextResponse.json({error:'Sheet Data Source kosong.'},{status:400});const period=inferPeriod(file.name)||new Date().toISOString().slice(0,7)+'-01';const rows=raw.map(r=>row(r,period));if(!rows.some(r=>r.amount!==0))return NextResponse.json({error:'Amount in local currency terbaca 0.'},{status:400});const db=adminClient();const {data:upload,error:upErr}=await db.from('grir_uploads').insert({file_name:file.name,period,row_count:rows.length,status:'success'}).select('id').single();if(upErr)throw upErr;const chunk=500;for(let i=0;i<rows.length;i+=chunk){const payload=rows.slice(i,i+chunk).map(r=>({...r,upload_id:upload.id}));const {error}=await db.from('grir_transactions').insert(payload);if(error){await db.from('grir_transactions').delete().eq('upload_id',upload.id);await db.from('grir_uploads').delete().eq('id',upload.id);throw error;}}return NextResponse.json({ok:true,period,rowCount:rows.length});}catch(e){console.error(e);return NextResponse.json({error:e?.message||'Upload gagal.'},{status:500});}}
